# Generated by Django 5.0.1 on 2024-01-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrations_railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='feeds',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
