# Generated by Django 5.0.1 on 2024-01-30 17:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations_railway', '0003_alter_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='feeds',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='FeedFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrations_railway.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrations_railway.user')),
            ],
            options={
                'db_table': 'feed_follows',
                'unique_together': {('user', 'feed')},
            },
        ),
    ]
