# Generated by Django 5.0.1 on 2024-01-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrations_railway', '0002_alter_feed_table_alter_post_table_alter_user_table'),
        ('migrations_railway', '0003_alter_name'),
    ]

    operations = [
    ]
